# Configuração DNSMASQ gerada por script
# Servidores DNS upstream
server=8.8.8.8
server=1.1.1.1

# Configurações básicas
listen-address=0.0.0.0
domain-needed
bogus-priv
no-resolv
no-poll
expand-hosts
cache-size=1000

# Domínio local
domain=flix.home
local=/flix.home/

# Resoluções locais
address=/jellyfin.flix.home/172.20.0.2
address=/sonarr.flix.home/172.20.0.3
address=/radarr.flix.home/172.20.0.4
address=/qbittorrent.flix.home/172.20.0.5
address=/heimdall.flix.home/172.20.0.6
address=/traefik.flix.home/172.20.0.7
address=/prowlarr.flix.home/172.20.0.8
address=/whoami.flix.home/172.20.0.9